name: Take Screenshot

on:
  push:
    branches:
      - main

jobs:
  take-screenshot:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install playwright-chromium

      - name: Take screenshot
        run: |
          npx playwright screenshot https://example.com
