name: Take Screenshot

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: "30 7 * * *"

jobs:
  take-screenshot:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Make sure we don't download the existing screenshots as part
        # of this process -- this Action is strictly append-only, so
        # don't waste limited LFS bandwidth on it.
        lfs: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Take screenshot
        run: bash take_screenshot.sh
