name: Take screenshots

on:
  push:
    branches:
      - main

  schedule:
    - cron: '7 7 * * 1'  # Every Monday at 7:07am UTC

jobs:
  take-screenshots:
    runs-on: macos-latest

    strategy:
      matrix:
        include:
          - url: alexwlchan.net
            screenshot_name: alexwlchan.net
          - url: books.alexwlchan.net
            screenshot_name: books

      # Setting max-parallel ensures that these jobs will run in serial,
      # not parallel, so we don't have conflicting tasks trying to
      # push new commits.
      max-parallel: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        with:
          # Make sure we don't download the existing screenshots as part
          # of this process -- this Action is strictly append-only, so
          # don't waste limited LFS bandwidth on it.
          lfs: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Take screenshot
        run: |
          today=$(date +"%Y-%m-%d")
          screenshot_path="screenshots/${{ matrix.screenshot_name }}.$today.png"

          mkdir -p "$(dirname "$screenshot_path")"

          if [[ -f "$screenshot_path" ]]; then exit 0; fi

          npm install playwright
          npx playwright install chromium

          npx playwright screenshot \
            --full-page \
            --wait-for-timeout 10000 \
            "${{ matrix.url }}" "$screenshot_path"

          # The actions/checkout step will check out the commit that
          # triggered this workflow, but main may have advanced if
          # a previous job pushed a commit.  Pull it first.
          git pull origin main

          # Add the new screenshot and push it to GitHub.
          git add "$screenshot_path"
          git commit -m "Add screenshot for ${{ matrix.url }} for $today"
          git push origin main
